# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)

        self.La = QtWidgets.QLabel(self.centralwidget)
        self.La.setFont(font)
        self.La.setText("Введите часы: ")
        self.La.setGeometry(0, 0, 231, 71)

        self.Lb = QtWidgets.QLabel(self.centralwidget)
        self.Lb.setFont(font)
        self.Lb.setText("Введите минуты: ")
        self.Lb.setGeometry(0, 70, 281, 71)


        self.Lc = QtWidgets.QLabel(self.centralwidget)
        self.Lc.setFont(font)
        self.Lc.setText("Введите часы: ")
        self.Lc.setGeometry(0, 160, 231, 71)

        self.Ly = QtWidgets.QLabel(self.centralwidget)
        self.Ly.setFont(font)
        self.Ly.setText("Введите минуты: ")
        self.Ly.setGeometry(0, 230, 281, 71)

        self.Le = QtWidgets.QLabel(self.centralwidget)
        self.Le.setFont(font)
        self.Le.setText("Прошло: ")
        self.Le.setGeometry(30, 350, 151, 71)

        self.Lf = QtWidgets.QLabel(self.centralwidget)
        self.Lf.setFont(font)
        self.Lf.setText("час(ов)")
        self.Lf.setGeometry(370, 360, 111, 71)

        self.Lf = QtWidgets.QLabel(self.centralwidget)
        self.Lf.setFont(font)
        self.Lf.setText("минут(а)")
        self.Lf.setGeometry(370, 430, 151, 41)

        self.Lt = QtWidgets.QLabel(self.centralwidget)
        self.Lt.setFont(font)
        self.Lt.setText("Начало отсчета")
        self.Lt.setGeometry(500, 50, 271, 71)

        self.Li = QtWidgets.QLabel(self.centralwidget)
        self.Li.setFont(font)
        self.Li.setText("Конец отсчета")
        self.Li.setGeometry(510, 190, 241, 71)




        self.LEa = QtWidgets.QLineEdit(self.centralwidget)
        self.LEa.setFont(font)
        self.LEa.setGeometry(190, 10, 191, 51)
        self.LEb = QtWidgets.QLineEdit(self.centralwidget)
        self.LEb.setFont(font)
        self.LEb.setGeometry(230, 80, 191, 51)
        self.LEc = QtWidgets.QLineEdit(self.centralwidget)
        self.LEc.setFont(font)
        self.LEc.setGeometry(190, 170, 191, 51)
        self.LEy = QtWidgets.QLineEdit(self.centralwidget)
        self.LEy.setFont(font)
        self.LEy.setGeometry(230, 240, 191, 51)


        self.LEh = QtWidgets.QLineEdit(self.centralwidget)
        self.LEh.setFont(font)
        self.LEh.setGeometry(160, 370, 191, 51)
        self.LEh.setReadOnly(True)

        self.LEk = QtWidgets.QLineEdit(self.centralwidget)
        self.LEk.setFont(font)
        self.LEk.setGeometry(160, 430, 191, 51)
        self.LEk.setReadOnly(True)

        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setFont(font)
        self.btn.setText("Найти")
        self.btn.setGeometry(550, 370, 241, 81)
        self.btn.clicked.connect(self.cloc)




        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def cloc(self):
        x1 = int(self.LEa.text())
        x2 = int(self.LEb.text())
        y1 = int(self.LEc.text())
        y2 = int(self.LEy.text())
        y1 -= x1
        if x2 > y2:
            y1 -= 1
            y2 = 60 - (x2-y2)
        else:
            y2 -= x2
        self.LEh.setText(str(y1))
        self.LEk.setText(str(y2))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())